services:
  - type: web
    name: anonimbot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python anonimbot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: REVEAL_PRICE_STARS
        value: "50"
